---
upload_path: "/content/uploads"
frontmatter_file_url_template: ""
body_file_url_template: "/uploads"
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  post:
    default_front_matter_template: post
version: 0.25.1
