---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: Title of the post
- name: description
  label: Description
  type: text
  hidden: false
  default: Some description for SEO
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 2017-07-27 00:00:00 +0200
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
